### ISSUE TITLE
Target Speed on Car

### ISSUE THREAD

**Issue by prajwalthakur** [bosky2001/f1tenth_mppi#1]
Hi, I noticed that the target speed specified in the "on car" branch is just only 1.5 m/s. what was the limitation /issue you faced when you tried increasing the target speed?
[target-speed](https://github.com/bosky2001/f1tenth_mppi/blob/53bcf6617c4025dde508532d0c311c98788dbea2/scripts/mppi_node.py#L664)

**Comment by bosky2001** [comment]
Hey, I think it was due to the control frequency on the car being around 10-15ish Hz and having a higher target speed would mean that we would need a higher response rate for it to work
